name: Diff Helm Charts
description: This action renders Helm charts from the current branch and the default branch and compares the rendered charts
runs:
  using: composite
  steps:
  - uses: yokawasa/action-setup-kube-tools@v0.11.1
    with:
      setup-tools: |
        helm

  - name: Checkout code
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      fetch-depth: 0

  - name: Render Helm chart (current branch)
    shell: bash
    run: |
      for chart in charts/*; do
        helm template $chart >> "${chart}_current.yaml"
      done
      cat *.yaml > $CURRENT

  - name: Checkout default branch
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.repository.default_branch }}

  - name: Render Helm chart (default branch)
    shell: bash
    run: |
      for chart in charts/*; do
        helm template $chart > "${chart}_default.yaml"
      done
      cat *.yaml > $DEFAULT

  - name: Diff Helm charts
    shell: bash
    run: |
      for chart in charts/*; do
        diff $DEFAULT $CURRENT
      done
