name: Diff Helm Charts
description: This action renders Helm charts from the current branch and the default branch and compares the rendered charts
runs:
  using: composite
  steps:
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.pull_request.head.ref }}

  - name: Render Helm chart (current branch)
    shell: bash
    run: |
      for chart in charts/*; do
        helm dep build $chart
        helm template $chart >> "${{ runner.temp }}/current.yaml"
      done

  - name: Checkout default branch
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.repository.default_branch }}

  - name: Render Helm chart (default branch)
    shell: bash
    run: |
      for chart in charts/*; do
        helm dep build $chart
        helm template $chart >> "${{ runner.temp }}/default.yaml"
      done

  - name: Diff Helm charts
    shell: bash
    continue-on-error: true
    run: |
      cat "Echo Default"
      cat "${{ runner.temp }}/default.yaml"
      cat "Echo Current"
      cat "${{ runner.temp }}/current.yaml"
      echo "```" >> "${{ runner.temp }}/diff.yaml"
      diff -u "${{ runner.temp }}/default.yaml" "${{ runner.temp }}/current.yaml" >> "${{ runner.temp }}/diff.yaml"
      echo "```" >> "${{ runner.temp }}/diff.yaml"
      cat "${{ runner.temp }}/diff.yaml"
      cat "${{ runner.temp }}/diff.yaml" >> $GITHUB_STEP_SUMMARY
