name: Test chart diff
on:
  pull_request:
  push:
    branches-ignore:
      - ${{ github.event.repository.default_branch }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: pjstaab/chart-diff@test
